site_name: ""
site_description: binjr, a time series browser
site_url: https://binjr.eu/
copyright: This website is licensed under a Creative Commons Attribution 4.0 International License.
repo_url: https://github.com/binjr/binjr/
edit_uri: ""

nav:
  - About:
    - about/what_is_binjr.md
    - about/features.md
    - about/supported_data_sources.md
    - about/notice.md
  - Docs:
    - documentation/getting-started.md
    - documentation/troubleshooting.md
    - documentation/verify-signature.md
    - "User guide":
        - documentation/user_guide/main.md
        - documentation/user_guide/sources.md
        - documentation/user_guide/editing_parsing_profiles.md
        - documentation/user_guide/worksheets.md
        - documentation/user_guide/charts_worksheets.md
        - documentation/user_guide/logs_worksheets.md
        - documentation/user_guide/workspaces.md
        - documentation/user_guide/settings.md
        - documentation/user_guide/shortcuts.md
  - Download:
    - download/latest_release.md
    - download/plugins.md
    - download/CHANGELOG.md
  - Blog:
    - blog/index.md

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  logo: assets/images/binjr_logo.png
#  font: false
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - content.code.select
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode

  highlightjs: true
  hljs_languages:
    - java
    - sh

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - meta
  - smarty
  - extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: False
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog:
      enabled: true
      post_date_format: long
      post_url_date_format: yyyy/MM
  - rss:
      feed_title: "binjr"
      match_path: "blog.posts.*"
      image: "https://binjr.eu/assets/images/binjr_avatar.png"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      abstract_chars_count: -1
      abstract_delimiter: ""

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/binjr
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@binjr
